name: CI-Production

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.0'

      - name: Install dependencies
        run: npm run fresh-install

      - name: Build libraries
        run: npm run build

      - name: Allow AppArmor sandbox to work on Ubuntu
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
        # A safer option to fix sandboxes if Chrome is installed on a local client:
        # echo -e "\nexport CHROME_DEVEL_SANDBOX=/opt/google/chrome/chrome-sandbox" >> ~/.bashrc

      - name: Start server
        run: npm run workflow-test

      - name: Test server response
        run: npm test

      - name: Stop server after testing
        run: npm stop
